[[ECOS]]
arch = "i686"
git-tree-sha1 = "0c6f26f53a3417ae438d69e33040f27b66e1715e"
libc = "musl"
os = "linux"

    [[ECOS.download]]
    sha256 = "79d4a54a7bb8e03fbcd07da54a65da9876a1353de5463a6aaacae53bde9ebbc7"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.5+0/ECOS.v2.0.5.i686-linux-musl.tar.gz"
[[ECOS]]
arch = "aarch64"
git-tree-sha1 = "0b425594f21a41744669f8c9fa9f0b5ed12d5ef3"
libc = "musl"
os = "linux"

    [[ECOS.download]]
    sha256 = "5dee604c875111fa7cb3c4d4d5fafc94b453eb571409aaa1e67f0e4223fdce58"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.5+0/ECOS.v2.0.5.aarch64-linux-musl.tar.gz"
[[ECOS]]
arch = "i686"
git-tree-sha1 = "a0000c15e4442ae0495781af51cd5339867b4c5f"
os = "windows"

    [[ECOS.download]]
    sha256 = "4f7853d4613444053ad448943347155f08e28e9a0fd76cc1b7d4cd869981ff94"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.5+0/ECOS.v2.0.5.i686-w64-mingw32.tar.gz"
[[ECOS]]
arch = "x86_64"
git-tree-sha1 = "c4af151a712e42a176663c0cf87b44587c9708c0"
os = "windows"

    [[ECOS.download]]
    sha256 = "97ee59af174115b494c00dbb70a59aefd7d8bd8e8bf1301f31531d5b16436154"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.5+0/ECOS.v2.0.5.x86_64-w64-mingw32.tar.gz"
[[ECOS]]
arch = "armv7l"
git-tree-sha1 = "26334c03c211329e219a536e1b568e5541686a00"
libc = "glibc"
os = "linux"

    [[ECOS.download]]
    sha256 = "777b2094316520526e2744dd222179af9b657ee7887896721378aa16ec4175dc"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.5+0/ECOS.v2.0.5.armv7l-linux-gnueabihf.tar.gz"
[[ECOS]]
arch = "armv7l"
git-tree-sha1 = "11000ad07cb6ef30ea97f3f0bcf6d79196330ae1"
libc = "musl"
os = "linux"

    [[ECOS.download]]
    sha256 = "fccb2f36e6f5963f35c62cdc963e40a776ced614894ed9de14d0b3bb2ae47ac7"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.5+0/ECOS.v2.0.5.armv7l-linux-musleabihf.tar.gz"
[[ECOS]]
arch = "i686"
git-tree-sha1 = "b724cf1352ddd3a84cc045259342c8fee4e08b49"
libc = "glibc"
os = "linux"

    [[ECOS.download]]
    sha256 = "491de190d1a7c7994297e42ffff7b0c08d135e99e70ba71664dbfb95faf076e7"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.5+0/ECOS.v2.0.5.i686-linux-gnu.tar.gz"
[[ECOS]]
arch = "x86_64"
git-tree-sha1 = "b49ea645faf142e03d14cb0411e65ccd47e5d390"
libc = "glibc"
os = "linux"

    [[ECOS.download]]
    sha256 = "344458ba78047416243fc2853a9c05cfa4c99be2143417df5af01be565c702f7"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.5+0/ECOS.v2.0.5.x86_64-linux-gnu.tar.gz"
[[ECOS]]
arch = "powerpc64le"
git-tree-sha1 = "1e71ce2d3f03b65e272464b80fb940be691b0520"
libc = "glibc"
os = "linux"

    [[ECOS.download]]
    sha256 = "23010be796f4b925b4c9578bf751eb2e4f816bdc2fa0905f194167b6c522fe39"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.5+0/ECOS.v2.0.5.powerpc64le-linux-gnu.tar.gz"
[[ECOS]]
arch = "x86_64"
git-tree-sha1 = "7438522e088fdf66fefe059b5f110fb469ef366a"
os = "macos"

    [[ECOS.download]]
    sha256 = "a5bfcc5370be56f7a6cc9899691abeeab22b579959abfcfe0004472f84c2f838"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.5+0/ECOS.v2.0.5.x86_64-apple-darwin14.tar.gz"
[[ECOS]]
arch = "aarch64"
git-tree-sha1 = "1388b29f23cb17704f08c743ca2c3cb267e7a8c2"
libc = "glibc"
os = "linux"

    [[ECOS.download]]
    sha256 = "300a133a5e693708ecd7b7cdb5d4a206e3361b6f80897b99dd2beadf270fc7f3"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.5+0/ECOS.v2.0.5.aarch64-linux-gnu.tar.gz"
[[ECOS]]
arch = "x86_64"
git-tree-sha1 = "51931da3dd28d371d5828709e5cb3a55f7da6397"
os = "freebsd"

    [[ECOS.download]]
    sha256 = "621f385c107126dea1ac13c2be2b0fef70c81f301433595276c4ee1a20baed47"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.5+0/ECOS.v2.0.5.x86_64-unknown-freebsd11.1.tar.gz"
[[ECOS]]
arch = "x86_64"
git-tree-sha1 = "8f892cd715fb6f26ee09693dd82676583ba353f1"
libc = "musl"
os = "linux"

    [[ECOS.download]]
    sha256 = "43f26915e0fb94c9cc3d6e22cd071ac58473873428db893866f9a8230f8316e4"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.5+0/ECOS.v2.0.5.x86_64-linux-musl.tar.gz"
