[[ECOS]]
arch = "aarch64"
git-tree-sha1 = "c5a4c507d53fea220b3b307f49f9a4b90b1a1854"
libc = "glibc"
os = "linux"

    [[ECOS.download]]
    sha256 = "b21ba4608d9008d878b787ca1eb108fed47018adc8307985eea3a3e1078e9822"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+1/ECOS.v2.0.8.aarch64-linux-gnu.tar.gz"
[[ECOS]]
arch = "aarch64"
git-tree-sha1 = "12cfa1ae0d3390a9c4657e00826948353d05888b"
libc = "musl"
os = "linux"

    [[ECOS.download]]
    sha256 = "1997aadf70c88a0c9cb60f4af8005bd5ea8a2d73bd2867ef527ca5379d57be37"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+1/ECOS.v2.0.8.aarch64-linux-musl.tar.gz"
[[ECOS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d636462395c800e1fb55b8229c16ee8d11fc9821"
libc = "glibc"
os = "linux"

    [[ECOS.download]]
    sha256 = "6d6d9c9575447e6891cf31ec33c405d1c7b0f3d52a2f00aa8da28b2dde7d4e82"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+1/ECOS.v2.0.8.armv7l-linux-gnueabihf.tar.gz"
[[ECOS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "78b60d35efbd5904ff916a4eccaf4d545f2481c9"
libc = "musl"
os = "linux"

    [[ECOS.download]]
    sha256 = "48485d99d883acf10b0ff99d58c4264e04c46abb9db8749443b87ba02077943e"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+1/ECOS.v2.0.8.armv7l-linux-musleabihf.tar.gz"
[[ECOS]]
arch = "i686"
git-tree-sha1 = "a0728a4a3dcb82cad384e2014757595e080f52c6"
libc = "glibc"
os = "linux"

    [[ECOS.download]]
    sha256 = "41f1dc32fce3cd5b2cb8c481c5158af06f2e6dd722fc7ce324e32baabf7adca6"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+1/ECOS.v2.0.8.i686-linux-gnu.tar.gz"
[[ECOS]]
arch = "i686"
git-tree-sha1 = "5f1c4b458e9f874524d125bb6a2273290e7171f6"
libc = "musl"
os = "linux"

    [[ECOS.download]]
    sha256 = "65c149ed0ba9ca3822f8242b068b87dbee72c3940555875cb38f9209c597471b"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+1/ECOS.v2.0.8.i686-linux-musl.tar.gz"
[[ECOS]]
arch = "i686"
git-tree-sha1 = "05d4962f350e9d3cde85260d3ddc00495fb75b8f"
os = "windows"

    [[ECOS.download]]
    sha256 = "0cef0824c4aeb27cdb7d7db76819aefcacb6eb7263f1fa1be5040b9f46c4fd60"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+1/ECOS.v2.0.8.i686-w64-mingw32.tar.gz"
[[ECOS]]
arch = "powerpc64le"
git-tree-sha1 = "e5a13e8f4fb67f5913de95bef7265b780a035268"
libc = "glibc"
os = "linux"

    [[ECOS.download]]
    sha256 = "961e0c81fc1c1b259fc8365ff5b0c8aee72df6c227c2010162af76e57dd72dd8"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+1/ECOS.v2.0.8.powerpc64le-linux-gnu.tar.gz"
[[ECOS]]
arch = "x86_64"
git-tree-sha1 = "2b6081783ec240c40171e55a8409f69098688a0b"
os = "macos"

    [[ECOS.download]]
    sha256 = "3a337768e5db499eb43810a2b58694dfba7b7c7d28d0ff4456d7245265f224d8"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+1/ECOS.v2.0.8.x86_64-apple-darwin.tar.gz"
[[ECOS]]
arch = "x86_64"
git-tree-sha1 = "9e955599dce7ac1fa9cefe8216c121efae37cf87"
libc = "glibc"
os = "linux"

    [[ECOS.download]]
    sha256 = "c021e0f0709c762deea79a92bc836c2dadc118c00fa0c174b360fa5248ea6f5d"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+1/ECOS.v2.0.8.x86_64-linux-gnu.tar.gz"
[[ECOS]]
arch = "x86_64"
git-tree-sha1 = "600c3ab6d94ff52288235d267d8c542231602bb4"
libc = "musl"
os = "linux"

    [[ECOS.download]]
    sha256 = "39944a44d221b2a145ec491b7db9d423d22a2a4e7b1c1c994ce0c462fadf4952"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+1/ECOS.v2.0.8.x86_64-linux-musl.tar.gz"
[[ECOS]]
arch = "x86_64"
git-tree-sha1 = "acc9c7d827232f2b120f47969b56b22e71d459f2"
os = "freebsd"

    [[ECOS.download]]
    sha256 = "5e3f4d51ef370a4904ad66640c566c30cad14d77070fd81d7f2aa4465a0706ce"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+1/ECOS.v2.0.8.x86_64-unknown-freebsd.tar.gz"
[[ECOS]]
arch = "x86_64"
git-tree-sha1 = "344d77fd87e815f0e569251fae10ce06c30a531a"
os = "windows"

    [[ECOS.download]]
    sha256 = "35b51d398b48d25905863ca91119d5e3a556323eb1ac441b5c81f07bdfde2613"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+1/ECOS.v2.0.8.x86_64-w64-mingw32.tar.gz"
