[[ECOS]]
arch = "aarch64"
git-tree-sha1 = "22feb942e22068e3c37a13ed9d94ea44938f89cd"
libc = "glibc"
os = "linux"

    [[ECOS.download]]
    sha256 = "424f9def83166be51d9064a85224dabacc04dc8caf3f300c8d6973e9d2a46382"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+0/ECOS.v2.0.8.aarch64-linux-gnu.tar.gz"
[[ECOS]]
arch = "aarch64"
git-tree-sha1 = "8420e9452570b06159a38ac55636eea4eabf475b"
libc = "musl"
os = "linux"

    [[ECOS.download]]
    sha256 = "1439baf5e911e23e5f6079ef88e3074d8006ecadfc50f9452e29d9bdf5c8f152"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+0/ECOS.v2.0.8.aarch64-linux-musl.tar.gz"
[[ECOS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1560d2e3a254d8e80c631aad50dff155cc03c32f"
libc = "glibc"
os = "linux"

    [[ECOS.download]]
    sha256 = "643bffefd032072167340a8990909020f2a6a608373ab9a4b5f28e9d169a5599"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+0/ECOS.v2.0.8.armv7l-linux-gnueabihf.tar.gz"
[[ECOS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "00e2b3bfbb8fe4339ce77ae4f17564f2cfcdc314"
libc = "musl"
os = "linux"

    [[ECOS.download]]
    sha256 = "463bce42121d1affbc3a9fa539b4439979fe501bfcc982f9ba0fed3645777d49"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+0/ECOS.v2.0.8.armv7l-linux-musleabihf.tar.gz"
[[ECOS]]
arch = "i686"
git-tree-sha1 = "05a8750b57ddbf38722ddebb552d15c500e4a215"
libc = "glibc"
os = "linux"

    [[ECOS.download]]
    sha256 = "c182047d44c1c28ff045e70b2c474902100b80f8cf3c408a02ab4cb4b1f08139"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+0/ECOS.v2.0.8.i686-linux-gnu.tar.gz"
[[ECOS]]
arch = "i686"
git-tree-sha1 = "7450871082ed16b6000aab72ac7d9ae8520a046f"
libc = "musl"
os = "linux"

    [[ECOS.download]]
    sha256 = "153f46c80e4d55af3bb9ea174b9e0f062a498d639183b417a2ba1c1bbd6258d0"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+0/ECOS.v2.0.8.i686-linux-musl.tar.gz"
[[ECOS]]
arch = "i686"
git-tree-sha1 = "bfb861a06adaed09070ff0ec96bf83cc5dae1f96"
os = "windows"

    [[ECOS.download]]
    sha256 = "dd908de352360e878ac58503541195cd713590aa90b1c3b69c0a430d7c7811b0"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+0/ECOS.v2.0.8.i686-w64-mingw32.tar.gz"
[[ECOS]]
arch = "powerpc64le"
git-tree-sha1 = "e3943732da306a0485719351106aadf47b7597a5"
libc = "glibc"
os = "linux"

    [[ECOS.download]]
    sha256 = "e29ec5865b7500148dbfa7f4c219e08ffe3204d869affb2e803775dfee9659af"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+0/ECOS.v2.0.8.powerpc64le-linux-gnu.tar.gz"
[[ECOS]]
arch = "x86_64"
git-tree-sha1 = "40b782c70d77b481d850f63bdda7294c62c16e9f"
os = "macos"

    [[ECOS.download]]
    sha256 = "09d91a53b0120ee51ecf43aa59c860d74beed93f832139ef6c3aced240447e44"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+0/ECOS.v2.0.8.x86_64-apple-darwin.tar.gz"
[[ECOS]]
arch = "x86_64"
git-tree-sha1 = "7851e90eebdd723cd26d27708664c99d728d254c"
libc = "glibc"
os = "linux"

    [[ECOS.download]]
    sha256 = "3bd6091b62d39455951cad75588ac14a0dabeb920967d6474cfbbd3031c63708"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+0/ECOS.v2.0.8.x86_64-linux-gnu.tar.gz"
[[ECOS]]
arch = "x86_64"
git-tree-sha1 = "d9cf19a1079c06ad6e47a06d687a7dd2ce94f4a6"
libc = "musl"
os = "linux"

    [[ECOS.download]]
    sha256 = "3bc4f60f174d6b941ea2b1cf194a5ce52e862db6987b6c7d22a448f23f8a4499"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+0/ECOS.v2.0.8.x86_64-linux-musl.tar.gz"
[[ECOS]]
arch = "x86_64"
git-tree-sha1 = "76fb8dc682e30781d6eddf5bc1940c01d71dd794"
os = "freebsd"

    [[ECOS.download]]
    sha256 = "7507555ffc21b0674bc2a924c6615afd71c56072614eb22b9067753d02ddc267"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+0/ECOS.v2.0.8.x86_64-unknown-freebsd.tar.gz"
[[ECOS]]
arch = "x86_64"
git-tree-sha1 = "7e80370d46fb593b3128666e5a9f048da396127c"
os = "windows"

    [[ECOS.download]]
    sha256 = "3a78719298fbb101114906de4f5344a751b65715d662e9a902b5f9f01abf59b9"
    url = "https://github.com/JuliaBinaryWrappers/ECOS_jll.jl/releases/download/ECOS-v2.0.8+0/ECOS.v2.0.8.x86_64-w64-mingw32.tar.gz"
