# Autogenerated wrapper script for ECOS_jll for aarch64-apple-darwin
export libecos

JLLWrappers.@generate_wrapper_header("ECOS")
JLLWrappers.@declare_library_product(libecos, "@rpath/libecos.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libecos,
        "lib/libecos.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
