# Autogenerated wrapper script for ECOS_jll for x86_64-w64-mingw32
export libecos

JLLWrappers.@generate_wrapper_header("ECOS")
JLLWrappers.@declare_library_product(libecos, "libecos.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libecos,
        "bin\\libecos.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
